import Head from 'next/head'
import {Inter} from '@next/font/google'
import HomePage from "@/pages/HomePage";
import Navbar from "@/pages/Navbar";
import Footer from "@/pages/Footer";
import {useState} from "react";


const inter = Inter({subsets: ['latin']})

export default function Home() {
    //const [regModal, setRegModel] = useState(false) //Modal toggle state for Registration button
    const [loginModal, setLoginModal] = useState(false) //Modal toggle state for Login button
    const [isAuth, setIsAuth] = useState(false)

    return (
        <div className="my-body dark:bg-black">
            <Head>
                <title>HaloGate Movies</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <Navbar
                isAuth={isAuth}
                setIsAuth={setIsAuth}
                loginModal={loginModal}
                setLoginModal={setLoginModal}
                // regModal={regModal}
                // setRegModal={setRegModel}
            />

            <HomePage/>
            <Footer
                isAuth={isAuth}
                loginModal={loginModal}
                setLoginModal={setLoginModal}
            />
        </div>
    )
}
