import Head from 'next/head'
import {Inter} from '@next/font/google'
import HomePage from "@/pages/HomePage";
import Navbar from "@/pages/Navbar";
import Footer from "@/pages/Footer";
import {useContext, useState} from "react";
import {UserState} from "@/pages/StateContext";



const inter = Inter({subsets: ['latin']})

export default function Home() {
    const { loginModal, setLoginModal, isAuth, setIsAuth } = useContext(UserState);
    //const [loginModal, setLoginModal] = useState(false) //Modal toggle state for Login button

    const [query, setQuery] = useState("")

    return (
        <>
            <div className="my-body dark:bg-black">
                <Head>
                    <title>HaloGate Movies</title>
                    <meta name="description" content="Generated by create next app"/>
                    <meta name="viewport" content="width=device-width, initial-scale=1"/>
                    <link rel="icon" href="/favicon.ico"/>
                </Head>

                <Navbar
                    isAuth={isAuth}
                    setIsAuth={setIsAuth}
                    loginModal={loginModal}
                    setLoginModal={setLoginModal}
                    query={query}
                    setQuery={setQuery}
                    // regModal={regModal}
                    // setRegModal={setRegModel}
                />

                <HomePage
                    query={query}
                    setQuery={setQuery}
                    isAuth={isAuth}
                />
                <Footer
                    isAuth={isAuth}
                    loginModal={loginModal}
                    setLoginModal={setLoginModal}
                />
            </div>
        </>

    )
}
